language: python
python:
  - "3.3"
  - "2.7"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - make python

# command to run tests, e.g. python setup.py test
script:
  - make test_python

notifications:
  email: false
