language: python
python:
- '3.3'
- '2.7'
- pypy
install:
- make python
script:
- make test_python
notifications:
  email: false
env:
  global:
    secure: pM1RWGnjss8+LtPAKZ0n34To57IRCTCAvmSbViyrnHjJLVLck5/bRSR9n5gCdP9aG4+1kSDMzfdmYdEZeW3LCP8PEX3Dcz4cWXk+RFidWIliVVBJgJiwKVO1bHOx1mIiqUEGPusvL3g8zU4s2qXcYsGenPQwoEaLOnrRsg8x23w=
